/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.67.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Params for creation keyword rules
type KeywordRulesParams struct {
	// Keyword rule definitions. The minimum number of rule definitions is 1. The maximum number of rule definitions is 100.
	KeywordRules []KeywordRuleParams `json:"keywordRules"`
}
