/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.67.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Set of logical sub-transactions that a transaction should get split into
type SplitTransactionsParams struct {
	// List of sub-transactions
	SubTransactions []SubTransactionParams `json:"subTransactions"`
}
