/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.67.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Container for data of multiple bank connections
type BankConnectionList struct {
	// List of bank connections
	Connections []BankConnection `json:"connections"`
}
