/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.67.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Set of identifiers (in ascending order)
type IdentifierList struct {
	// Set of identifiers (in ascending order)
	Identifiers []int64 `json:"identifiers,omitempty"`
}
