/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.67.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Container for keyword rules
type KeywordRuleList struct {
	// List of keyword rules
	KeywordRules []KeywordRule `json:"keywordRules"`
}
