/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.67.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Identifiers params
type IdentifiersParams struct {
	// List of identifiers
	Ids []int64 `json:"ids"`
}
