/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.67.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Container for data of multiple notification rules
type NotificationRuleList struct {
	// List of notification rules
	NotificationRules []NotificationRule `json:"notificationRules,omitempty"`
}
