/*
 * finAPI RESTful Services
 *
 * finAPI RESTful Services
 *
 * API version: v1.67.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Container for category edit params
type EditCategoryParams struct {
	// New name of the category. Maximum length is 128.
	Name string `json:"name"`
}
